# Generated by Django 5.0.4 on 2024-04-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentid",
            options={"ordering": ["student_id"]},
        ),
    ]
