# Generated by Django 5.0.4 on 2024-04-30 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_subject_subjectmarks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subjectmarks",
            options={"verbose_name_plural": "student marks"},
        ),
        migrations.CreateModel(
            name="ReportCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.IntegerField()),
                ("date_of_generation", models.DateField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studentreportcard",
                        to="student.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "date_of_generation")},
            },
        ),
    ]
